### ISSUE TITLE
Python 3.7 complains about `collections.Set` etc references being deprecated and moved to `collections.abc`

### ISSUE THREAD

**Issue by autumnjolitz** [pasztorpisti/py-flags#11]
When I run `python -X dev myproject.py` (which uses py-flags), I see messages like
```
software/project/python/lib/python3.7/site-packages/flags.py:121: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  elif isinstance(members, (tuple, list, collections.Set)):
```

One approach to handle this is:

```
try:
    from collections import Set, Iterable
except ImportError:
    from collections.abc import Set, Iterable
```

Alternatively, fixing your minimum support to Python 3.3 and changing all references from `collections.{Set, Iterable, ...}` to `collections.abc.{...}` would also solve the issue.

**Comment by pasztorpisti** [comment]
Fixed. Thanks for reporting.

The old py-flags worked with python 3.8.1 but it was complaining that that it would stop working in 3.9. :-D
