### ISSUE TITLE
Truth-testing of Flags class raises exception

### ISSUE THREAD

**Issue by kwohlfahrt** [pasztorpisti/py-flags#3]
According to the [python docs](https://docs.python.org/3/library/stdtypes.html#truth-value-testing), it should be legal to test any object (including classes) for truth value. As far as I can tell, most user-defined classes evaluate to `True`. Napoleon for example relies on this behaviour, see the snippet below:

```
cls_is_owner = (cls and hasattr(cls, name) and
                name in cls.__dict__)
```

Unfortunately, `Flags` raises an exception:

```
>>> bool(flags.Flags)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kjw53/.local/lib/python3.5/site-packages/flags.py", line 394, in __len__
    return len(cls.__members_without_aliases__)
  File "/home/kjw53/.local/lib/python3.5/site-packages/flags.py", line 380, in __getattr__
    return super().__getattribute__('__all_members__')[name]
AttributeError: type object 'Flags' has no attribute '__all_members__'
```

The source of this seems to be that if `__bool__` is not defined on a class, it falls back to checking `__len__` returns non-zero (see the doc link above), and `__len__` raises the exception.

I think this could be fixed by adding `def __bool__(self): return True` to `FlagsMeta`, but let me know if there are any problems with that approach.

`FlagsMeta` itself seems to be fine:

```
>>> bool(flags.FlagsMeta)
True
```

**Comment by Paebbels** [comment]
What is the semantic of `bool(flag)`? Always returning `True` is no semantic.

One could argue that a flag is true if at least one bit is set otherwise false.

**Comment by pasztorpisti** [comment]
@kwohlfahrt Makes sense. I'm having a look.

@Paebbels The original question is a bit tricky, it asks for the truth value of the flags classes, not the flags instances.

**Comment by pasztorpisti** [comment]
The new v1.1.1 version is ready for `pip install`.

**Comment by pasztorpisti** [comment]
Thanks for the report. This was a bug. It was an issue only in case of "abstract" flags classes that didn't have any members/flags defined. A related bug it that `len(Flags)` should return 0 for abstract flags classes instead of raising but unfortunately I didn't think about this before creating the `v1.1.1` release. I'm going to create a quick `v1.1.2` :-).

**Comment by kwohlfahrt** [comment]
Looks good, thanks for the quick fix!
