### ISSUE TITLE
Python 3.6 added Flags

### ISSUE THREAD

**Issue by Paebbels** [pasztorpisti/py-flags#4]
Hello,

Python 3.6 added `Flag` and `IntFlag`. It would be nice if the Python version becomes as powerful as your solution. Maybe you can share some ideas with them.

https://docs.python.org/3/library/enum.html#intflag

Kind regards
    Patrick

**Comment by pasztorpisti** [comment]
Hi Patrick!

In case of standard libraries one has to be very carful when it comes to adding new features. Std libs are expected to be backward compatible with python version changes and it is more difficult to remove superfluous or not-so-well designed features. For this reason I think adding only the basic functionality is a good idea, later they can extend it if there is a demand for mature ideas. I'm pretty sure that those guys are good - and they are probably aware of alternative flag-implementations and can find out what features they have. Unfortunately I'm too busy with my life to become an active member of the python community.

In case of a pypi library (like this `py-flags` thingy) it is somewhat easier. I increase the version, I make a backward-incompatible change (e.g.: removing a feature), and ask the people to pin the previous version of the lib (if they haven't done it yet for some reason) till adapting their code to my new interface.

Cheers,
István

**Comment by Paebbels** [comment]
Hello István,

the idea for this issue was, to make both sides aware of each others implementations :).
From a users perspective, It would be nice to reduce the number of external dependencies, especially since Python has already Enums and now Flags.

Personally, I have no problem in running `pip install -r requirements.txt` to setup my Python environment for a script or program, but some users and contributors have expressed their concerns. OTOH, what fore is PyPI and PIP, if not to load hundreds of little library pieces, so developers don't reinvent the wheel :).

**Comment by pasztorpisti** [comment]
Running `pip install -r requirements.txt` is unavoidable if you are writing larger software. The std lib usually isn't enough and not everything makes its way to the std lib.

However, flags is a relatively basic library which might become widely used by other libraries. In that case it would be practical to use the same flags implementation in all libraries - this would make their integration simpler in some cases.
