### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by tiborbeck** [pasztorpisti/py-flags#5]
Which version of python supports a * argument?

Python 2.6.8 (unknown, Nov  7 2012, 14:47:45) 
[GCC 4.1.2 20080704 (Red Hat 4.1.2-52)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from flags import Flags
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lun/exporter/src/e/lib/python2.6/site-packages/flags.py", line 66
    def create_flags_subclass(base_enum_class, class_name, flags, *, mixins=(), module=None, qualname=None,
                                                                              ^
SyntaxError: invalid syntax

**Comment by IlyaSkriblovsky** [comment]
This is "keywords-only arguments" syntax from Python 3.

This library is py3-only

**Comment by pasztorpisti** [comment]
@tiborbeck This library is python3.2+ compatible.

The python3.6+ standard lib has an `enum.Flags` class which has the same basic functionality as this lib.

The author of the `aenum` library claims to provide similar flags feature for python2.7 [as discussed here](http://stackoverflow.com/a/42642901/3059438).

Unfortunately your python is quite old (2.6). The most straightforward options are:
- Searching for another python2.6 compatible flags library
- Not using a flags library in your project
- Upgrading to python2.7 and using the `aenum` library
- Trying to port `aenum` to your python2.6
