### ISSUE TITLE
SyntaxError: def create_flags_subclass

### ISSUE THREAD

**Issue by noxxer** [pasztorpisti/py-flags#6]
- py-flags version: 1.1.2
    Python version: 2.7.6
    Operating System: Ubuntu 14.04.3 LTS

  File "/usr/local/lib/python2.7/dist-packages/flags.py", line 66
    def create_flags_subclass(base_enum_class, class_name, flags, *, mixins=(), module=None, qualname=None,
                                                                   
SyntaxError: invalid syntax

What caused the error and how can I resolve it?

**Comment by pasztorpisti** [comment]
`py-flags` works only with python3.

Under python2 you can get similar functionality using the https://pypi.python.org/pypi/aenum package.

From python 3.6+ the standard `enum` package has `enum.Flag` and `enum.IntFlag`.
